---
- name: Configure
  hosts: all
  gather_facts: false
  tasks:
    - name: "Make credential"
      ansible.eda.credential:
        name: "Alertmanager"
        inputs:
          auth_type: "basic"
          username: "alertmanager"
          password: "p@ssw0rd"
        credential_type_name: "basic"
        organization: "Default"
      host: "{{ item.host }}"
      with_items:
        - host: "https://18.224.138.176"
          username: "admin"
          password: "Admin!Password!Gw"

    - name: Make event stream
      ansible.eda.event_stream:
        name: "Alertmanager"
        credential_name: "Alertmanager"
      host: "{{ item.host }}"
      with_items:
        - host: "https://18.224.138.176"
          username: "admin"
          password: "Admin!Password!Gw"
